apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: default
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: 'rabbitmq-server'
        static_configs:
          - targets:
              - 'production-ready.rabbitmq-system:15692'
      - job_name: worker-monitor-flight
        static_configs:
        - targets:
          - mimir-worker-monitor.production:80
      - job_name: pgpool-stats
        static_configs:
        - targets:
          - pgpool-stats.hotel:9714
      - job_name: worker-monitor-holidays
        static_configs:
        - targets:
          - worker-monitor.production-aahol:80
      - job_name: mysql_exporter
        static_configs:
        - targets:
          - mysql-exporter:9104
      - job_name: redis_exporter
        static_configs:
        - targets:
          - redis-nodeexporter.default:9121
          - redis-nodeexporter.production:9121
          - redis-nodeexporter.production-aahol:9121
      - job_name: hms-pgpool2_exporter
        static_configs:
        - targets:
          - pgpool-stats.hotel:9719